from pygame.math import Vector2
from pygame import USEREVENT


CELL_SIZE = 25
NUM_OF_CELLS = 30
WINDOW_WIDTH = NUM_OF_CELLS * CELL_SIZE
WINDOW_HEIGHT = NUM_OF_CELLS * CELL_SIZE
FRAME_RATE = 60
CLOCK = ()
WINDOW = ()
FOOD = ()
SNAKE = ()
SNAKE_MOVE = USEREVENT + 1
SNAKE_INIT_X = 7
SNAKE_INIT_Y = 3
VELOCITY = 150
MOVE_RIGHT = Vector2(1,0)
MOVE_LEFT = Vector2(-1,0)
MOVE_TOP = Vector2(0,-1)
MOVE_BOTTOM = Vector2(0,1)
FOOD_IMG = ()
ICON = ()
